#
# ServiceAccount for staticwebsite-operator
#
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: staticwebsite-operator
  labels:
    app.kubernetes.io/name: staticwebsite-operator
    app.kubernetes.io/version: v1alpha1
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/part-of: staticwebsite-platform
    app.kubernetes.io/component: controller

imagePullSecrets:
  - name: staticwebsite-operator