#
# The secret which stores the dockerConfigJSON to pull the image from docker hub
#
---
apiVersion: v1
kind: Secret
metadata:
  name: staticwebsite-operator
  labels:
    app.kubernetes.io/name: staticwebsite-operator
    app.kubernetes.io/version: v1alpha1
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/part-of: staticwebsite-platform
    app.kubernetes.io/component: controller
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${DOCKER_CONFIG_JSON}