#
# The cluster role defining the permissions to manage the resources
#
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-actions-cd
  labels:
    app.kubernetes.io/name: github-actions-cd
    app.kubernetes.io/component: cd-pipeline
rules:
  # Apply CRD manifests
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    verbs: [ "get", "list", "create", "update", "patch", "delete" ]

  # Apply RBAC manifests for the operator
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: ["clusterroles", "clusterrolebindings"]
    verbs: [ "get", "list", "create", "update", "patch", "delete" ]

  # Manage the operator Deployment and its ServiceAccount
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "list", "create", "update", "patch", "delete" ]

  # manage the other resources
  - apiGroups: [ "" ]
    resources: [ "serviceaccounts", "namespaces", "secrets", "configmaps", "services", "pods" ]
    verbs: [ "get", "list", "create", "update", "patch", "delete" ]