#
# The service account used by CD workflow to authenticate to cluster and manages the resources in staticwebsite-operator namespace
#
apiVersion: v1
kind: ServiceAccount

metadata:
  name: github-actions-cd
  namespace: staticwebsite-operator
  labels:
    app.kubernetes.io/name: github-actions-cd
    app.kubernetes.io/component: cd-pipeline
